services:
  bot:
    image: chiupam/tgbot:latest
    container_name: bot
    environment:
      - TELEGRAM_API_ID=12345678
      - TELEGRAM_API_HASH=your_api_hash
      - TELEGRAM_PHONE=+86138xxxxxxxx
      - SESSION_PATH=/app/data/bot.session
      - CONFIG_DIR=/app/data
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true
